# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\python_project\qt_gui\Children_Ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(776, 509)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(70, 20, 166, 380))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Device_Lable = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Device_Lable.setFont(font)
        self.Device_Lable.setObjectName("Device_Lable")
        self.verticalLayout.addWidget(self.Device_Lable)
        self.ExperimentInfo_Label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.ExperimentInfo_Label.setFont(font)
        self.ExperimentInfo_Label.setObjectName("ExperimentInfo_Label")
        self.verticalLayout.addWidget(self.ExperimentInfo_Label)
        self.Appointer_Label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Appointer_Label.setFont(font)
        self.Appointer_Label.setObjectName("Appointer_Label")
        self.verticalLayout.addWidget(self.Appointer_Label)
        self.Data_Label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Data_Label.setFont(font)
        self.Data_Label.setObjectName("Data_Label")
        self.verticalLayout.addWidget(self.Data_Label)
        self.Begin_Label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Begin_Label.setFont(font)
        self.Begin_Label.setObjectName("Begin_Label")
        self.verticalLayout.addWidget(self.Begin_Label)
        self.End_Label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.End_Label.setFont(font)
        self.End_Label.setObjectName("End_Label")
        self.verticalLayout.addWidget(self.End_Label)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(230, 20, 350, 380))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.lineEdit_ExperimentInfo = QtWidgets.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.lineEdit_ExperimentInfo.setFont(font)
        self.lineEdit_ExperimentInfo.setObjectName("lineEdit_ExperimentInfo")
        self.verticalLayout_2.addWidget(self.lineEdit_ExperimentInfo)
        self.lineEdit_Appointer = QtWidgets.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.lineEdit_Appointer.setFont(font)
        self.lineEdit_Appointer.setObjectName("lineEdit_Appointer")
        self.verticalLayout_2.addWidget(self.lineEdit_Appointer)
        self.lineEdit_Data = QtWidgets.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.lineEdit_Data.setFont(font)
        self.lineEdit_Data.setObjectName("lineEdit_Data")
        self.verticalLayout_2.addWidget(self.lineEdit_Data)
        self.lineEdit_Begin = QtWidgets.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.lineEdit_Begin.setFont(font)
        self.lineEdit_Begin.setObjectName("lineEdit_Begin")
        self.verticalLayout_2.addWidget(self.lineEdit_Begin)
        self.lineEdit_End = QtWidgets.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.lineEdit_End.setFont(font)
        self.lineEdit_End.setObjectName("lineEdit_End")
        self.verticalLayout_2.addWidget(self.lineEdit_End)
        self.Start_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Start_Button.setGeometry(QtCore.QRect(220, 440, 200, 60))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Start_Button.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/ac39.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Start_Button.setIcon(icon)
        self.Start_Button.setIconSize(QtCore.QSize(64, 64))
        self.Start_Button.setObjectName("Start_Button")
        self.End_Button = QtWidgets.QPushButton(self.centralwidget)
        self.End_Button.setGeometry(QtCore.QRect(490, 440, 200, 60))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.End_Button.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/a2_15.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.End_Button.setIcon(icon1)
        self.End_Button.setIconSize(QtCore.QSize(64, 64))
        self.End_Button.setObjectName("End_Button")
        self.Deylay_Label = QtWidgets.QLabel(self.centralwidget)
        self.Deylay_Label.setGeometry(QtCore.QRect(60, 390, 81, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.Deylay_Label.setFont(font)
        self.Deylay_Label.setObjectName("Deylay_Label")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setGeometry(QtCore.QRect(20, 450, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setMaximum(5.0)
        self.doubleSpinBox.setSingleStep(0.2)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.lineEdit_EBL1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_EBL1.setGeometry(QtCore.QRect(600, 100, 47, 47))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.lineEdit_EBL1.setFont(font)
        self.lineEdit_EBL1.setObjectName("lineEdit_EBL1")
        self.lineEdit_EBL2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_EBL2.setGeometry(QtCore.QRect(680, 100, 47, 47))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.lineEdit_EBL2.setFont(font)
        self.lineEdit_EBL2.setObjectName("lineEdit_EBL2")
        self.EBL_Lable_1 = QtWidgets.QLabel(self.centralwidget)
        self.EBL_Lable_1.setGeometry(QtCore.QRect(610, 30, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.EBL_Lable_1.setFont(font)
        self.EBL_Lable_1.setObjectName("EBL_Lable_1")
        self.EBL_Lable_2 = QtWidgets.QLabel(self.centralwidget)
        self.EBL_Lable_2.setGeometry(QtCore.QRect(680, 30, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.EBL_Lable_2.setFont(font)
        self.EBL_Lable_2.setObjectName("EBL_Lable_2")
        self.EBL_Lable_3 = QtWidgets.QLabel(self.centralwidget)
        self.EBL_Lable_3.setGeometry(QtCore.QRect(640, 150, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.EBL_Lable_3.setFont(font)
        self.EBL_Lable_3.setObjectName("EBL_Lable_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Device_Lable.setText(_translate("MainWindow", "设备"))
        self.ExperimentInfo_Label.setText(_translate("MainWindow", "实验描述"))
        self.Appointer_Label.setText(_translate("MainWindow", "预约人"))
        self.Data_Label.setText(_translate("MainWindow", "日期"))
        self.Begin_Label.setText(_translate("MainWindow", "开始"))
        self.End_Label.setText(_translate("MainWindow", "结束"))
        self.comboBox.setItemText(0, _translate("MainWindow", "新磁控"))
        self.comboBox.setItemText(1, _translate("MainWindow", "EBL"))
        self.comboBox.setItemText(2, _translate("MainWindow", "MJB4光刻机"))
        self.comboBox.setItemText(3, _translate("MainWindow", "新电子束蒸发"))
        self.Start_Button.setText(_translate("MainWindow", "开始"))
        self.End_Button.setText(_translate("MainWindow", "终止"))
        self.End_Button.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.Deylay_Label.setText(_translate("MainWindow", "延时间隔"))
        self.EBL_Lable_1.setText(_translate("MainWindow", "套刻"))
        self.EBL_Lable_2.setText(_translate("MainWindow", "非套刻"))
        self.EBL_Lable_3.setText(_translate("MainWindow", "EBL参数"))
import button_rc
