# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\python_project\qt_gui\Parent_Ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(685, 600)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Login_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Login_Button.setGeometry(QtCore.QRect(230, 390, 240, 120))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Login_Button.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/ac1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Login_Button.setIcon(icon)
        self.Login_Button.setIconSize(QtCore.QSize(72, 72))
        self.Login_Button.setObjectName("Login_Button")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(80, 150, 531, 231))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.User_Label = QtWidgets.QLabel(self.frame)
        self.User_Label.setGeometry(QtCore.QRect(10, 60, 150, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.User_Label.setFont(font)
        self.User_Label.setObjectName("User_Label")
        self.Password_Label = QtWidgets.QLabel(self.frame)
        self.Password_Label.setGeometry(QtCore.QRect(10, 160, 150, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Password_Label.setFont(font)
        self.Password_Label.setObjectName("Password_Label")
        self.Username_Text = QtWidgets.QLineEdit(self.frame)
        self.Username_Text.setGeometry(QtCore.QRect(119, 80, 301, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Username_Text.setFont(font)
        self.Username_Text.setMaxLength(20)
        self.Username_Text.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.Username_Text.setObjectName("Username_Text")
        self.Password_Text = QtWidgets.QLineEdit(self.frame)
        self.Password_Text.setGeometry(QtCore.QRect(119, 170, 301, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Password_Text.setFont(font)
        self.Password_Text.setMaxLength(20)
        self.Password_Text.setObjectName("Password_Text")
        self.Main_Pic = QtWidgets.QLabel(self.centralwidget)
        self.Main_Pic.setGeometry(QtCore.QRect(230, 20, 241, 171))
        self.Main_Pic.setText("")
        self.Main_Pic.setPixmap(QtGui.QPixmap(":/icons/Main.png"))
        self.Main_Pic.setObjectName("Main_Pic")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 685, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/a2_36.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.actionAbout.setFont(font)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setCheckable(False)
        self.actionExit.setEnabled(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/a2_17.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.actionExit.setFont(font)
        self.actionExit.setObjectName("actionExit")
        self.menuMenu.addAction(self.actionAbout)
        self.menuMenu.addAction(self.actionExit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ez_Experiement"))
        self.Login_Button.setText(_translate("MainWindow", "登陆"))
        self.User_Label.setText(_translate("MainWindow", "账号"))
        self.Password_Label.setText(_translate("MainWindow", "密码"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
import button_rc
